/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeleteEmailArgs } from "./DeleteEmailArgs";
import { EmailFindManyArgs } from "./EmailFindManyArgs";
import { EmailFindUniqueArgs } from "./EmailFindUniqueArgs";
import { Email } from "./Email";
import { EmailService } from "../email.service";
@graphql.Resolver(() => Email)
export class EmailResolverBase {
  constructor(protected readonly service: EmailService) {}

  async _emailsMeta(
    @graphql.Args() args: EmailFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Email])
  async emails(@graphql.Args() args: EmailFindManyArgs): Promise<Email[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => Email, { nullable: true })
  async email(
    @graphql.Args() args: EmailFindUniqueArgs
  ): Promise<Email | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Email)
  async deleteEmail(
    @graphql.Args() args: DeleteEmailArgs
  ): Promise<Email | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
