/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeleteBloodTypeArgs } from "./DeleteBloodTypeArgs";
import { BloodTypeFindManyArgs } from "./BloodTypeFindManyArgs";
import { BloodTypeFindUniqueArgs } from "./BloodTypeFindUniqueArgs";
import { BloodType } from "./BloodType";
import { BloodTypeService } from "../bloodType.service";
@graphql.Resolver(() => BloodType)
export class BloodTypeResolverBase {
  constructor(protected readonly service: BloodTypeService) {}

  async _bloodTypesMeta(
    @graphql.Args() args: BloodTypeFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [BloodType])
  async bloodTypes(
    @graphql.Args() args: BloodTypeFindManyArgs
  ): Promise<BloodType[]> {
    return this.service.findMany(args);
  }

  @graphql.Query(() => BloodType, { nullable: true })
  async bloodType(
    @graphql.Args() args: BloodTypeFindUniqueArgs
  ): Promise<BloodType | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => BloodType)
  async deleteBloodType(
    @graphql.Args() args: DeleteBloodTypeArgs
  ): Promise<BloodType | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
